# 菜单配置（若不需要某项可直接删除）
menu:
  # 首页
  - id: home
    link: /
    icon: home
    class: menu-home
  # 归档
  - id: archives
    link: /archives
    icon: archive
    class: menu-archive
  # 目录
  - id: category
    link: javascript:;
    category: true
    icon: bookmark
    class: menu-category
    # 读书
  #- id: reading
  #  link: /reading
  #  icon: book
  #  class: menu-reading
  # 标签云
  - id: tags
    link: /tags
    icon: tags
  # 留言板 
  - id: saidlist
    link: /saidlist
    icon: book
    class: menu-about
  # 关于 
  - id: about
    link: /about
    icon: user
    class: menu-about
  # 搜索
  - id: search
    link: "#search"
    icon: search
    class: menu-search modal-trigger

# 颜色配置 https://materializecss.com/color.html#palette
color:
  header: cyan darken-2
  footer: cyan darken-2
  page_nav: cyan darken-2
  side_nav: cyan darken-2
  tag: teal lighten-1
  article_title_link: blue-grey
  link: teal
  pagination: teal
  tab: teal
  archive_item: grey
  fab: teal
  fab_2: green
  fab_3: yellow darken-1
  new: pink
  about_header: cyan darken-2
  about_title: indigo

archive_yearly: true

# 版权信息
copyright: 粤ICP备16022296号 © 2015-2018 qianxunclub.com, All rights reserved. 

# Disqus评论shortname，若为空则不启用
disqus_shortname:
# 多说shortname，若为空则不启用
duoshuo_shortname:
# 网易云跟帖productKey，从通用代码中获取，若为空则不启用
yungentie_product_key:
# 畅言
changyan_appid: cysuusGWK

# Google分析track id，若为空则不启用
google_analytics:
# 腾讯分析sId，若为空则不启用
tencent_analytics: 

# 百度统计
baidu_token: 

# 百度收录
baidu_union_verify: 

# 百度收录 https://ziyuan.baidu.com
baidu_site_verification: D7tG2r0DD4

# 谷歌收录 https://www.google.com/webmasters/tools/home?hl=zh-CN
google_site_verification: 

# 高亮的主题，若为空则使用默认主题
google_code_prettify: prettify-tomorrow-night-eighties

# 是否启用MathJax数学公式渲染。如果你确认整个站点的博文都不会用到Latex数学公式，可以将其该项设为false提高页面加载速度
mathjax: true

# 是否启用网页计数器（使用不蒜子插件）
page_stat: true
